# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    allow:
      - dependency-type: 'all'
    ignore:
      - dependency-name: '@angular/*'
      - dependency-name: '@angular-devkit/*'
      - dependency-name: '@angular-eslint/*'
      - dependency-name: '@nx/*'
      - dependency-name: '@schematics/angular'
      - dependency-name: '@typescript-eslint/*'
      - dependency-name: 'angular-split'
      - dependency-name: 'eslint'
      - dependency-name: 'ng-packagr'
      - dependency-name: 'nx'
      - dependency-name: 'typescript'
      - dependency-name: 'zone.js'
