name: Check for new NX version
on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight
  workflow_dispatch:
permissions: write-all
jobs:
  update-nx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: timonmasberg/nx-migration-gh-action@v1.1.13
        with:
          repoToken: ${{ steps.generate-token.outputs.token }}
          prTitle: 'Migrates NX to $VERSION'
          includeMigrationsFile: false
          base: 'main'
